services:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
    ports:
      - "4443:4443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    environment :
      - DOMAIN_NAME=sponthus.42.fr
    restart: always
    # env_file:
    #   - .env

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    env_file:
      - .env

networks:
  network:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USE/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USE/data/mariadb