services:

    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb
        volumes:
                - mariadb:/var/lib/mysql:rw
        env_file:
            - .env
        networks:
            - network
        restart: always

    wordpress:
        container_name: wordpress
        image: wordpress
        env_file:
            - .env
        build:
            context: requirements/wordpress
        depends_on:
            - mariadb 
        volumes:
            - wordpress:/var/www/wordpress:rw
        networks:
            - network
        restart: always

    nginx:
        container_name: nginx
        image: nginx
        build:
            context: requirements/nginx
        ports:
            - "443:443"
        restart: always
        volumes:
            - wordpress:/var/www/wordpress:rw
        networks:
            - network
        depends_on:
            - wordpress

volumes :
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/sponthus/data/mariadb
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/sponthus/data/wordpress

networks:
    network:
        driver: bridge
  