services:

  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
    ports:
      - "443:443"
    restart: always
    # volumes:
    #   - ./nginx/conf/:/etc/nginx/conf.d/:ro
    networks:
      - network
    environment :
      - DOMAIN_NAME=sponthus.42.fr
    # env_file:
    #   - .env

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /home/sponthus/data:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
networks:
  network:
    driver: bridge