version: "3"
services:

  nginx:
    container_name: nginx-container
    build: 
      context: requirements/nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    networks:
      - network
    environment :
      - DOMAIN_NAME=sponthus.42.fr
    # env_file:
    #   - .env

networks:
  network:
    driver: bridge